# Generated by Django 3.0.3 on 2020-04-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HtmlStylingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='uploadimage')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploadimage')),
                ('filename', models.CharField(blank=True, max_length=120, null=True)),
                ('gist_id', models.CharField(blank=True, max_length=120, null=True)),
                ('gist_filename', models.CharField(blank=True, max_length=120, null=True)),
                ('video_src', models.CharField(blank=True, max_length=200, null=True)),
                ('language_choice', models.CharField(blank=True, choices=[('Python', 'python'), ('React', 'react'), ('Both', 'both')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('using_from', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('language_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_blog.TechStack')),
            ],
        ),
    ]
