# Generated by Django 3.0.4 on 2020-04-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechFeatures',
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
