# Generated by Django 3.0.3 on 2020-03-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='uploadimage'),
            preserve_default=False,
        ),
    ]
