# Generated by Django 3.0.4 on 2020-04-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_auto_20200413_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('using_from', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('language_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_blog.TechStack')),
            ],
        ),
    ]
