# Generated by Django 3.0.4 on 2020-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_auto_20200319_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
