# Generated by Django 3.0.3 on 2020-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
