# Generated by Django 3.0.4 on 2020-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0003_techfeatures_techstack'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_from', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('skills_used', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
            ],
        ),
    ]
