# Generated by Django 3.0.4 on 2020-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0004_workexperiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiece',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploadimage'),
        ),
    ]
