# Generated by Django 3.0.3 on 2020-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0004_post_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=120),
        ),
    ]
