# Generated by Django 3.0.3 on 2020-03-15 11:33

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0005_auto_20200315_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
