# Generated by Django 3.0.3 on 2020-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0006_auto_20200315_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
