# Generated by Django 3.0.4 on 2020-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0007_auto_20200330_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_src',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
