# Generated by Django 3.0.4 on 2020-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
