# Generated by Django 3.0.4 on 2020-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0009_auto_20200330_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gist_filename',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gist_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
