# Generated by Django 3.0.4 on 2020-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0010_auto_20200330_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gist_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_src',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
