# Generated by Django 3.0.3 on 2020-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0010_auto_20200425_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='related_to',
            field=models.ManyToManyField(to='api_blog.KnownTech'),
        ),
    ]
