# Generated by Django 3.0.4 on 2020-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0011_auto_20200330_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gist_filename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
