# Generated by Django 3.0.3 on 2020-04-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0011_auto_20200425_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlstylingchange',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
