# Generated by Django 3.0.3 on 2020-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0012_htmlstylingchange_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlstylingchange',
            name='html_file',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
