# Generated by Django 3.0.3 on 2020-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0012_auto_20200330_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language_choice',
            field=models.CharField(choices=[('Python', 'python'), ('React', 'react'), ('Both', 'both')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
