# Generated by Django 3.0.3 on 2020-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0013_post_language_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('completed', models.BooleanField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='language_choice',
            field=models.CharField(blank=True, choices=[('Python', 'python'), ('React', 'react'), ('Both', 'both')], max_length=10, null=True),
        ),
    ]
