# Generated by Django 3.0.4 on 2020-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0015_auto_20200405_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlStylingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=200)),
            ],
        ),
    ]
