# Generated by Django 3.0.3 on 2020-04-05 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0015_auto_20200404_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
