# Generated by Django 3.0.3 on 2020-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0016_auto_20200405_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
