# Generated by Django 3.0.3 on 2020-04-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0017_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('using_from', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tech',
        ),
        migrations.AddField(
            model_name='techfeatures',
            name='language_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_blog.TechStack'),
        ),
    ]
