# Generated by Django 3.0.3 on 2020-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0018_auto_20200413_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techstack',
            name='skill',
        ),
        migrations.AddField(
            model_name='techfeatures',
            name='skill',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techstack',
            name='using_from',
            field=models.IntegerField(),
        ),
    ]
