# Generated by Django 3.0.3 on 2020-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0019_auto_20200413_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfeatures',
            name='skill',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
